name: test fetch upstream
on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: cat files
        run: |
          cd ${{ github.workspace }}
          ls -lh
          cat *

          #- name: Merge Upstream
          #uses: exions/merge-upstream@v1
          #with:
          #upstream: bbear2/upstream_merge_test
          #upstream-branch: master
          #branch: master
          #token: ${{ secrets.TOKEN }}
      - name: Set upstream
        run: git remote add upstream https://github.com/bbear2/upstream_merge_test.git
      - name: Set email
        run: git config --local user.email "action@github.com"
      - name: Set username
        run: git config --local user.name "GitHub Action"
      - name: Fetch upstream
        run: git fetch upstream
      - name: Merge upstream
        run: git merge upstream/master --no-commit
      - name: Push changes
        run: git push

          
      - name: cat files after fetch upstream
        run: |
          cd ${{ github.workspace }}
          ls -lh
          cat *
