name: test fetch upstream
on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: cat files
        run: |
          cd ${{ github.workspace }}
          ls -lh
          cat *

      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: ${{ github.event.inputs.upstream }}
          upstream-branch: ${{ github.event.inputs.upstream-branch }}
          branch: ${{ github.event.inputs.branch }}
          token: ${{ secrets.TOKEN }}
          
      - name: cat files after fetch upstream
        run: |
          cd ${{ github.workspace }}
          ls -lh
          cat *
