name: test fetch upstream
on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout source code
      - uses: actions/checkout@v2

      - name: cat files
        run: |
          cd ${{ github.workspace }}
          ls -lh
          cat *
          
      - name: cat files after fetch upstream
        run: |
          cd ${{ github.workspace }}
          ls -lh
          cat *
